name: strategy_env
channels:
  - conda-forge  # Recommended for up-to-date packages
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - pytest
  - scipy
  - fastapi==0.104.1
  - uvicorn==0.24.0
  - pydantic==2.4.2
  - python-dateutil==2.8.2
